export default {
  '03': 'Produse agricole, de ferma, de pescuit, de silvicultura si produse conexe',
  '09': 'Produse petroliere, combustibil, electricitate si alte surse de energie',
  '14': 'Produse de minerit, metale de baza si produse conexe',
  '15': 'Alimente, bauturi, tutun si produse conexe',
  '16': 'Utilaje agricole',
  '18': 'Imbracaminte, incaltaminte, articole de voiaj si accesorii',
  '19': 'Produse din piele, materiale textile, din plastic si din cauciuc',
  '22': 'Imprimate si produse conexe',
  '24': 'Produse chimice',
  '30': 'Echipament informatic si accesorii de birou, cu exceptia mobilierului si a pachetelor software',
  '31': 'Masini, aparate, echipamente si consumabile electrice; iluminat',
  '32': 'Echipament de radio, televiziune, comunicatii, telecomunicatii si articole conexe',
  '33': 'Echipamente medicale, produse farmaceutice si produse de ingrijire personala',
  '34': 'Echipament de transport si produse auxiliare pentru transport',
  '35': 'Echipament de securitate, de lupta impotriva incendiilor, de politie si de aparare',
  '37': 'Instrumente muzicale, articole sportive, jocuri, jucarii, obiecte de artizanat, obiecte de arta si accesorii',
  '38': 'Echipamente de laborator, optice si de precizie (cu exceptia ochelarilor)',
  '39': 'Mobila (inclusiv mobila de birou), accesorii de mobilier, aparate de uz casnic (exclusiv dispozitive de iluminat) si produse de curatat',
  '41': 'Apa captata si epurata',
  '42': 'Echipamente industriale',
  '43': 'Utilaje pentru minerit, cariere de piatra si constructii',
  '44': 'Structuri si materiale de constructii; produse auxiliare pentru constructii (cu exceptia aparatelor electrice)',
  '45': 'Lucrari de constructii',
  '48': 'Pachete software si sisteme informatice',
  '50': 'Servicii de reparare si intretinere',
  '51': 'Servicii de instalare (cu exceptia programelor software)',
  '55': 'Servicii hoteliere, de restaurant si de vanzare cu amanuntul',
  '60': 'Servicii de transport (cu exceptia transportului de deseuri)',
  '63': 'Servicii de transport anexe si conexe; servicii de agentii de turism',
  '64': 'Servicii postale si de telecomunicatii',
  '65': 'Utilitati publice',
  '66': 'Servicii financiare si de asigurare',
  '70': 'Servicii imobiliare',
  '71': 'Servicii de arhitectura, de constructii, de inginerie si de inspectie',
  '72': 'Servicii IT: consultanta, dezvoltare de software, internet si asistenta',
  '73': 'Servicii de cercetare si de dezvoltare si servicii conexe de consultanta',
  '75': 'Servicii de administratie publica, de aparare si de asigurari sociale',
  '76': 'Servicii privind industria petrolului si a gazului',
  '77': 'Servicii pentru agricultura, silvicultura, horticultura, acvacultura si apicultura',
  '79': 'Servicii pentru intreprinderi: drept, marketing, consultanta, recrutare, tiparire si securitate',
  '80': 'Servicii de invatamant si formare profesionala',
  '85': 'Servicii de sanatate si servicii de asistenta sociala',
  '90': 'Servicii de evacuare a apelor reziduale, de eliminare a deseurilor, de igienizare si servicii privind mediul',
  '92': 'Servicii de recreere, culturale si sportive',
  '98': 'Alte servicii comunitare, sociale si personale'
}
